[package]
name = "elfcat"
version = "0.1.0"
authors = ["Ruslan Akbashev <ruslashev@gmail.com>"]
edition = "2018"
repository = "https://github.com/ruslashev/elfcat"
license = "Unlicense"

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
